const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0a0a0a",
    background: "#fafafa",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#0a0a0a",
    primaryForeground: "#ffffff",
    secondary: "#f5f5f5",
    secondaryForeground: "#0a0a0a",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    accent: "#e5e5e5",
    accentForeground: "#0a0a0a",
    destructive: "#0a0a0a",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    // Macro colors (kept as subtle tones for legibility)
    macroProtein: "#525252",
    macroCarbs: "#737373",
    macroFat: "#a3a3a3",
  },
  dark: {
    text: "#fafafa",
    tint: "#fafafa",
    background: "#000000",
    foreground: "#fafafa",
    card: "#111111",
    cardForeground: "#fafafa",
    primary: "#ffffff",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#fafafa",
    muted: "#1a1a1a",
    mutedForeground: "#a3a3a3",
    accent: "#262626",
    accentForeground: "#fafafa",
    destructive: "#fafafa",
    destructiveForeground: "#000000",
    border: "#262626",
    input: "#262626",
    macroProtein: "#a3a3a3",
    macroCarbs: "#737373",
    macroFat: "#525252",
  },
  radius: 14,
};

export default colors;
